name: Android Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
  EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_ANON_KEY }}
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  GOOGLE_PLAY_CREDENTIALS: ${{ secrets.GOOGLE_PLAY_CREDENTIALS }}

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Login to Expo
        run: eas login --non-interactive

      - name: Configure EAS
        run: |
          eas build:configure

      - name: Build Android APK
        run: eas build -p android --profile preview --non-interactive

      - name: Build Android App Bundle
        run: eas build -p android --profile production --non-interactive

      - name: Submit to Play Store
        run: eas submit -p android --latest --non-interactive

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: |
            android/app/build/outputs/apk/release/
            android/app/build/outputs/bundle/release/ 