name: Metro Bundler Health Check

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'
      - 'metro.config.js'
      - 'package.json'
      - 'app.json'
      - 'ios/**'
      - 'android/**'

jobs:
  metro-health-check:
    name: Check Metro bundler health
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Validate Metro configuration
        run: |
          if grep -q "getDefaultConfig" metro.config.js; then
            echo "✅ Metro config is properly configured."
          else
            echo "❌ Metro config is not properly set up."
            exit 1
          fi

      - name: Check Watchman
        run: |
          brew install watchman
          watchman --version
          watchman watch-list || echo "Setting up watchman for the first time"
          watchman watch .

      - name: Validate Metro bundler startup
        run: |
          # Start Metro in the background and give it time to initialize
          npx react-native start --port 8082 &
          METRO_PID=$!
          
          # Sleep for 30 seconds to allow Metro to start
          sleep 30
          
          # Check if Metro is running
          if ps -p $METRO_PID > /dev/null; then
            echo "✅ Metro bundler started successfully."
            kill $METRO_PID
            exit 0
          else
            echo "❌ Metro bundler failed to start properly."
            exit 1
          fi

      - name: Validate app.json architecture settings
        run: |
          if grep -q '"newArchitecture": false' app.json; then
            echo "✅ app.json correctly has newArchitecture disabled"
          else
            echo "❌ app.json does not have newArchitecture: false properly set"
            exit 1
          fi
          
      - name: Validate Metro dependencies
        run: |
          if npm list metro | grep -q "metro@"; then
            echo "✅ Metro dependency is properly installed"
          else
            echo "❌ Metro dependency is missing or not properly installed"
            exit 1
          fi
          
  metro-smoke-test:
    name: Run Metro smoke test
    runs-on: macos-latest
    needs: metro-health-check
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        
      - name: Install iOS dependencies
        run: |
          cd ios
          pod install
          cd ..
          
      - name: Make scripts executable
        run: |
          chmod +x scripts/*.sh
          chmod +x scripts/*.js
          
      - name: Run Metro smoke test
        run: |
          node scripts/metro-smoke-test.js
          
      - name: Upload test screenshot
        uses: actions/upload-artifact@v3
        with:
          name: metro-test-screenshot
          path: metro-test-screenshot.png
          if-no-files-found: error 