name: Security Audit

on:
  push:
    branches: [ main, production ]
  pull_request:
    branches: [ main, production ]

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run security audit
        run: npm run audit:launch
        
      - name: Check for sensitive files
        run: |
          if [ -f ".env" ]; then
            echo "❌ .env file found in repository"
            exit 1
          fi
          if [ -f ".env.production" ]; then
            echo "❌ .env.production file found in repository"
            exit 1
          fi
          
      - name: Verify package security
        run: npm audit --production
        
      - name: Check TypeScript compilation
        run: npm run tsc --noEmit
        
      - name: Run ESLint
        run: npm run lint
        
      - name: Check for outdated dependencies
        run: |
          npm outdated || true
          echo "⚠️ Review any outdated dependencies above" 